# Numpy 기초 - 1 

In [2]:
import numpy as np

## zeros & ones
: 0으로 채워진 numpy array를 만들 수 있음
: 1으로 채워진 numpy array를 만들 수 있음

In [3]:
zeros = np.zeros([3, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
zeros = np.zeros(1)
zeros

array([0.])

In [6]:
ones = np.ones([10])
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

다 5로 된 array를 사용하고 싶다면?? fifth?? nono

In [7]:
ones*5 #이렇게 곱하기를 이용한다. 

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### arange
: 연속적인 숫자가 담긴 array

In [10]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [12]:
arr = np.arange(4, 9) # 4부터 ~ 9바로 앞 (즉 8까지 )
arr

array([4, 5, 6, 7, 8])

**어떤 식으로 많이 사용되냐면, 일단 순서대로 배열해놓고, reshape를 사용 하는 것. **

In [14]:
arr = np.arange(9).reshape(3, 3, 1)
arr

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

# Index

In [15]:
nums = [1, 2, 3, 4, 5]

In [16]:
nums[2:]

[3, 4, 5]

In [17]:
nums = [1, 2, 3, 4, [1, 2, 3]]
nums

[1, 2, 3, 4, [1, 2, 3]]

In [19]:
nums[4]

[1, 2, 3]

In [20]:
arr[1][2] #(1, 2)에 있는 값 가져온다. 

array([5])

In [21]:
arr[1, 2] #이렇게 같이 써도 된다 

array([5])

# slicing

In [22]:
arr[1: ]

array([[[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [23]:
arr[1:, 1: ]

array([[[4],
        [5]],

       [[7],
        [8]]])

# boolean Indexing

In [24]:
data = np.random.randn(3, 3)
data

array([[ 1.05627765,  1.2887901 ,  1.10261884],
       [-0.36986487, -0.61665009,  0.83151141],
       [-0.12522491, -2.48249135, -0.71085742]])

In [25]:
data <= 0 #이렇게 

array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True]])

# Broadcast
: 연산하려는 서로 다른 두 개의 행렬의 shape가 같지 않지만
한쪽의 차원이라도 같거나, 또는 값의 갯수가 한 개 일때 
이를 여러 복사를 하여 연산을 한다. 

In [28]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
np.sum(arr) #각 요소의 전체 합

36

In [31]:
np.max(arr) #최대값

8

In [32]:
np.min(arr)#최소값

0

In [34]:
np.max(arr,0)

array([6, 7, 8])

In [35]:
np.mean(arr) #평균값

4.0

In [36]:
np.argmax(arr) # ~번째에 있는 수가 가장 크다는 것. 

8

In [37]:
np.argmin(arr)# ~번째에 있는 수가 가장 작다. 

0

In [38]:
arr = np.array([3, 4, 5, 2 ,3, 2, 2])
np.unique(arr) #중복 되는거 제외하고 나온다. 

array([2, 3, 4, 5])