# 1. pytorch basic

In [1]:
import numpy as np
import torch

In [2]:
#torch는 numpy와 비슷해서 np.arange(10)와 같이
#아래와 같이 표현할 수 있다. 
nums = torch.arange(10)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#shape도 바로 볼 수 있고
nums.shape

torch.Size([10])

In [4]:
#tensor라고 되어 있는 타입을 numpy로도 바로 변환 할 수 있다. 
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#reshape도 가능
nums.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
#random으로 만들기
randoms = torch.rand((3, 3))
randoms

tensor([[0.6578, 0.5684, 0.0194],
        [0.7082, 0.3746, 0.9010],
        [0.1735, 0.4148, 0.8745]])

In [7]:
#zeros로 만들기
zeros = torch.zeros((3, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#ones로 만들기
ones = torch.ones((3, 3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#이미 만들어져있는 모양대로 zeros 만들기 (zeros_like)
again_zeros = torch.zeros_like(ones)
again_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## pytorch operations 

In [10]:
#연산도 numpy와 유사하게 바로 broadcast가능
nums = torch.arange(10)
3*nums

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [11]:
nums = nums.reshape((5, 2))
nums + nums

tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14],
        [16, 18]])

In [12]:
#더하기
result = torch.add(nums, 10)
result

tensor([[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]])

## pytorch view

In [13]:
range_nums = torch.arange(9).reshape((3, 3))
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [14]:
#view는 reshape와 다를 것이 없어서 reshape를 권하긴 하지만 다른 코드를 해석할 때 필요하므로 배운다. 
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
range_nums.view(1, 9)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

## pytorch slice & Index

In [16]:
nums

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [17]:
#index
nums[1]

tensor([2, 3])

In [18]:
#slice
nums[1:, 1:]

tensor([[3],
        [5],
        [7],
        [9]])

## pytorch Compile
: numpy를 torch tensor로 불러오기

In [19]:
arr = np.array([1, 1, 1])
arr_torch = torch.from_numpy(arr)
arr_torch

tensor([1, 1, 1])

In [20]:
#형변환도 가능
arr_torch.float()

tensor([1., 1., 1.])

In [21]:
#GPU사용 - GPU 인식하면 자동으로 cuda 로 넘어가게 하는 것 GPU 없으면 cpu하고
device = 'cuda' if torch.cuda.is_available() else 'cpu'
arr_torch.to(device)
device

'cpu'

## pytorch AutoGrad
: 기울기를 줘서 학습이 되게 하는 것

In [22]:
x = torch.ones(2, 2, requires_grad = True)
y = x+2
x, y

(tensor([[1., 1.],
         [1., 1.]], requires_grad=True),
 tensor([[3., 3.],
         [3., 3.]], grad_fn=<AddBackward0>))

In [23]:
z = y*y*3
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [24]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [25]:
#train과정에서 기울기 구하려면
print(x.requires_grad)

True


In [26]:
#test과정에서 기울기를 구하지 않으려면
with torch.no_grad():
    print(x.requires_grad)

True
