# 내용
- 각 프레임워크 별 간단 tutorial
    - 시각화
    - Framework 기초 사용법
    - 예제 데이터 불러오고 다루기
    - layer구현 및 파악 & 모델 설계
    - 각 Framework별로 인공지능 학습
    
  ## TensorFlow 
  - 1.x에 비해 정말 쉬워짐,               
  - Numpy Array 와 호환이 쉬움        
  - TensorBoard, TFLite, TPU.         
  - 여전히 많은 사용자들이 사용
  
  ## PyTorch
  - Dynamic Graph & Define by Run
  - 쉽고 빠르며 파이써닉하다
  - 어마어마한 성장률

# TensorFlow 2.0 
: tensorflow 2.0 간단 사용법


In [1]:
import tensorflow as tf
tf.__version__

'2.0.0'

In [2]:
import numpy as np
import tensorflow as tf

## 1. Tensor 생성
- tuple이나 list 둘 다 np.array()로 씌어서 array를 만들수 있음

list 생성

In [5]:
[1, 2, 3]

[1, 2, 3]

array 생성

In [3]:
arr = np.array([1, 2, 2])
arr.shape

(3,)

In [4]:
arr = np.array([[1,2,3], [1, 2, 3]])
arr.shape

(2, 3)

### list를 tensor에 담기 

In [6]:
tf.constant([1, 2, 3]) #t이렇게 해주면 tensor가 생긴다. 

<tf.Tensor: id=0, shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

### tuple을 tensor에 담기

In [8]:
tf.constant(((1,2,3), (4, 5, 6)))

<tf.Tensor: id=1, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

### array를 tensor에 담기 ( 현업에서 가장 자주, 많이 쓰인다. )

In [10]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [13]:
tf.constant(arr)
tensor = tf.constant(arr)
tensor

<tf.Tensor: id=4, shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

## 2. Tensor에 담긴 정보 확인

In [14]:
tensor.shape

TensorShape([3])

### data type확인
- 주의 : Tensor 생성 할 때도 datatype을 정해주지 않기 때문에 datatype에 대한 혼동이 올 수 있음
- Datatype 에 따라 모델의무게나 성능 차이에도 영향을 줄 수 있음

In [15]:
tensor.dtype

tf.int64

#### data type정의 : 위에서 말한 혼동을 막기 위해 아에 정해놓고 갈 수도 있다. 

In [16]:
tf.constant([1, 2, 3], dtype = tf.float32)

<tf.Tensor: id=5, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

#### data type 변환 : 처음에 float였지만 int로 바꾸고 싶을 수도 있다. 
numpy에서 astype()을 주었듯이, tensor에서는 tf.cast이용

In [19]:
tf.cast(tensor, dtype = tf.uint8)

<tf.Tensor: id=6, shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

### tensor에서 Numpy 불러오기

In [20]:
np.array(tensor)

array([1, 2, 3])

## 3. 난수 생성

- numpy에서는 normal distribution이 기본적으로 실행된다 
그러나 
- tensor에서는 normal distribution과 uniform distribution으로 나눠진다. 

#### numpy에서의 난수 생성

In [22]:
# numpy에서는 normal distribution이 기본적으로 실행된다 그러나
np.random.randn(9) # 0<= ~ <9

array([-0.90381987,  0.22918563,  0.21257546,  0.25449657, -0.26272724,
        1.27007357, -0.34384877,  0.48367858,  0.69247133])

#### tensor에서의 난수 생성

In [4]:
#normal distribution
tf.random.normal([3, 3])

<tf.Tensor: id=5, shape=(3, 3), dtype=float32, numpy=
array([[-1.0329682 ,  0.00931551, -0.4154243 ],
       [ 0.60928506,  1.2722628 ,  0.8607203 ],
       [-0.17703654,  0.61430603,  0.21328032]], dtype=float32)>

In [6]:
#uniform distribution
tf.random.uniform([4, 4])

<tf.Tensor: id=12, shape=(4, 4), dtype=float32, numpy=
array([[0.33697045, 0.0336237 , 0.7026162 , 0.10408008],
       [0.79985225, 0.94964767, 0.83554924, 0.08478951],
       [0.88308036, 0.01189268, 0.21028137, 0.41764283],
       [0.7858132 , 0.01639926, 0.33391905, 0.6778507 ]], dtype=float32)>